# This workflow will build and deploy the hypha-workspace to GitHub Pages

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: hypha-workspace/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3

      - name: Install dependencies
        working-directory: hypha-workspace
        run: npm ci

      - name: Build hypha-workspace
        working-directory: hypha-workspace
        run: npm run build

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp -r hypha-workspace/dist/* deploy/
          cp -r hypha-workspace/out/* deploy/ 2>/dev/null || true
          cp hypha-workspace/index.html deploy/
          
          # Copy vscode-web files to static directory (proper approach)
          mkdir -p deploy/static
          if [ -d "hypha-workspace/node_modules/vscode-web/dist" ]; then
            cp -r hypha-workspace/node_modules/vscode-web/dist/* deploy/static/
          fi
          
          # Copy vscode-web assets to vscode-web directory
          mkdir -p deploy/vscode-web
          if [ -f "hypha-workspace/node_modules/vscode-web/dist/favicon.ico" ]; then
            cp hypha-workspace/node_modules/vscode-web/dist/favicon.ico deploy/vscode-web/
          fi
          if [ -f "hypha-workspace/node_modules/vscode-web/dist/manifest.json" ]; then
            cp hypha-workspace/node_modules/vscode-web/dist/manifest.json deploy/vscode-web/
          fi

      - name: Add .nojekyll file
        run: touch deploy/.nojekyll

      - name: Add CNAME file
        run: echo "ws.aicell.io" > deploy/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4
